package io.github.ih0rd.codegen;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Set;
import java.util.StringJoiner;
import java.util.TreeSet;

import io.github.ih0rd.polyglot.model.ContractClass;
import io.github.ih0rd.polyglot.model.ContractMethod;
import io.github.ih0rd.polyglot.model.ContractParam;

/**
 * Renders Java interface source files from parsed contracts.
 *
 * <p>The generator is deterministic: it collects imports from the rendered types, sorts them, and
 * adds a checksum header for the generated interface body.
 */
public final class JavaInterfaceGenerator {

  private static final String NL = System.lineSeparator();

  private static final String INTERFACE_BODY_TEMPLATE = "public interface %s {%n%n%s}%n";

  private static final String GENERATED_HEADER_TEMPLATE =
      "/**%n"
          + " * This file was generated by polyglot-codegen.%n"
          + " *%n"
          + " * SHA-256 checksum: %s%n"
          + " *%n"
          + " * Any manual changes will be overwritten.%n"
          + " */%n";
  private final JavaTypeRenderer renderer = new JavaTypeRenderer();

  /** Generates a complete Java source file for the given contract. */
  public String generate(ContractClass contract, String basePackage) {

    renderer.reset();

    StringBuilder methodsBuilder = new StringBuilder();

    // render methods first (so imports get collected)
    for (ContractMethod method : contract.methods()) {
      methodsBuilder.append(renderMethod(method)).append(NL);
    }

    Set<String> imports = new TreeSet<>(renderer.getImports());

    String interfaceBodyContent =
        String.format(INTERFACE_BODY_TEMPLATE, contract.name(), methodsBuilder);

    String checksum = sha256(interfaceBodyContent);

    StringBuilder file = new StringBuilder();

    file.append(String.format(GENERATED_HEADER_TEMPLATE, checksum));

    file.append("package ").append(basePackage).append(";").append(NL).append(NL);

    // imports
    if (!imports.isEmpty()) {
      for (String imp : imports) {
        file.append("import ").append(imp).append(";").append(NL);
      }
      file.append(NL);
    }

    file.append(interfaceBodyContent);

    return file.toString();
  }

  /** Calculates the SHA-256 checksum stored in the generated file header. */
  private String sha256(String content) {
    try {
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      byte[] hash = digest.digest(content.getBytes(StandardCharsets.UTF_8));
      StringBuilder hexString = new StringBuilder();
      for (byte b : hash) {
        String hex = Integer.toHexString(0xff & b);
        if (hex.length() == 1) {
          hexString.append('0');
        }
        hexString.append(hex);
      }
      return hexString.toString();
    } catch (NoSuchAlgorithmException e) {
      throw new RuntimeException("SHA-256 algorithm not available", e);
    }
  }

  /** Renders one Java method declaration. */
  private String renderMethod(ContractMethod method) {

    StringBuilder sb = new StringBuilder();

    String returnType = renderer.render(method.returnType());

    sb.append("    ")
        .append(returnType)
        .append(" ")
        .append(method.name())
        .append("(")
        .append(renderParams(method))
        .append(");");

    return sb.toString();
  }

  /** Renders the parameter list for a generated Java method. */
  private String renderParams(ContractMethod method) {

    StringJoiner joiner = new StringJoiner(", ");

    for (ContractParam param : method.params()) {
      joiner.add(renderer.render(param.type()) + " " + param.name());
    }

    return joiner.toString();
  }
}
